CREATE USER 'load'@'%' IDENTIFIED BY 'loadpwd';
GRANT ALL PRIVILEGES ON *.* TO 'load'@'%' IDENTIFIED BY 'loadpwd' WITH GRANT OPTION;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON testdb.* TO 'load'@'%' WITH GRANT OPTION;
